INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (36, 'Q18020504', 'Gerry Kuang', '匡坤刚', 'KQ0L60', 0, 0, 0);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (35, '10106101', 'Wayne Hua', '華清偉', 'KDL000', 2, 0, 2);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (34, '10004155', 'Benson Tsai', '蔡正輝', 'JMD500', 2, 0, 2);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (33, '8711121', 'INA LO', '羅美華', 'KQ1000', 2, 0, 2);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (32, '10702116', 'HP Wu', '吳弘斌', 'KQ1000', 2, 0, 2);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (31, '10303110', 'Steven Ho', '何誌勛', 'KQA000', 2, 0, 2);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (30, '8705119', 'JEFF WEI', '魏國珍', 'KQ0000', 2, 0, 2);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (29, 'Q08070810', 'XY Bai', '白新彥', 'KQAA00', 1, 1, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (28, 'Q1107Z456', 'Ada Gao', '高丹', '120F00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (27, '9508043', 'Tommy Lin', '林俊銘', '1STQ00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (26, 'Q12075800', 'Daniel Zhang', '張志超', '1R2Q00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (25, 'Q13050005', 'Peng Qing', '卿鵬', '1CK500', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (24, 'Q0909L800', 'Rhett Jia', '賈學軍', 'JMD3Q0', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (23, '10311045', 'Maxine SC Chang', '張詩筑', 'KQAH00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (22, 'Q1003BD30', 'Kenneth Shan', '陝振坤', 'KQ0U00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (21, '10005237', 'Jason CH Wang', '王家興', 'KQ0T00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (20, 'Q06011250', 'Gary Rui', '芮青江', '1K0MQ0', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (19, '9809106', 'Jacky Ch Chen', '陳俊煌', 'KQ1U00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (18, 'Q07070450', 'Meggie Liu', '劉曉燕', 'KQ0L00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (17, 'Q05045060', 'Juliet Zhu', '朱瓊', 'KQ1B00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (16, 'Q1207A410', 'Hum Ma', '馬江南', 'JMD120', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (15, 'Q13090021', 'Ting Tian', '田永川', 'KQ1N00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (14, 'Q11110336', 'Yadong Lu', '陸亞東', 'KQ1M00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (13, '10707103', 'Bryan WH Hung', '洪文賢', 'KQ1200', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (12, 'Q03030150', 'Angie Zhang', '張加峰', 'KQ1A00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (11, '9306122', 'CC Yao', '姚健忠', 'KQ1F00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (10, '9906120', 'Hank Hou', '侯世賢', 'KQ1S00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (9, '7507182', 'A.C.Chou', '鄒安照', 'KQ1W00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (8, 'Q06084250', 'Tony Fang', '方敏', 'KQ1R00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (7, 'Q08070380', 'Jack H Tan', '譚根華', 'KQ1E00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (6, 'Q07121320', 'Jie Zhou', '周傑', 'KQ1700', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (5, 'Q14090214', 'Andrew Zhou', '周東', 'KQ1600', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (4, '10604115', 'Thomas Ting', '丁德基', 'KQ1500', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (3, '9810101', 'Patrick Gan', '甘大龍', 'KQ1100', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (2, 'Q14110060', 'Jay J Chen', '陳傑', 'KQ1K00', 1, 2, 3);
INSERT INTO "komattendant" ("num", "empno", "ename", "cname", "deptid", "deptlevel", "status", "type") VALUES (1, '9910060', 'Vincent C Tsai', '蔡建安', 'KQ0F00', 1, 2, 3);
